// Solver: Q18 — Local Ollama Endpoint (Direct Solution)

export const id = 'q-ollama';
export const title = 'Q18: Local Ollama Endpoint';

export async function solve(email) {
  const directUrl = 'https://tds-roe-solver-api-t12026.onrender.com/q-ollama';

  return {
    type: 'solved',
    variant: 'Ollama Session Proxy & Diagnostics',
    answer: directUrl,
    answerDisplay: `### ⚠️ Backup Google Colab Solution Available\n\n**Q10, Q18, and Q25** are special cases involving user-specific environments, APIs, or dynamic data. These questions are not reliably solvable through the public solver interface for every user, so repeatedly trying them on the solver may waste your time.\n\nTo address this, we have prepared a dedicated Colab-based solution:\n\n📓 **Colab Link:** [Open Colab Workspace](https://colab.research.google.com/drive/1pVBlYAwBpQUqRhM9pUeX6Wt2CJWF6orH?usp=sharing)\n\n*Before running the Colab, edit Cell 1 and replace:* \n* \`YOUR_EMAIL\` with your IITM exam email\n* \`NGROK_TOKEN\` with your ngrok auth token\n\n---\n\n### 🤖 Ollama Proxy & Diagnostics Hub\n\nResolve this question instantly online:\n\n1. Open the **Ollama Proxy Hub**:\n   [${directUrl}](${directUrl})\n2. Follow the online guide to initialize a session and test compatibility.\n3. Enter your student email, start your ngrok tunnel, and paste the computed URL into the exam portal!\n\n**What it does:** Proxies requests to a local Ollama instance via an ngrok tunnel, providing an OpenAI-compatible API endpoint.`,
    guide: `### ⚠️ Backup Google Colab Solution Available\n\n**Q10, Q18, and Q25** are special cases involving user-specific environments, APIs, or dynamic data. These questions are not reliably solvable through the public solver interface for every user, so repeatedly trying them on the solver may waste your time.\n\nTo address this, we have prepared a dedicated Colab-based solution:\n\n📓 **Colab Link:** [Open Colab Workspace](https://colab.research.google.com/drive/1pVBlYAwBpQUqRhM9pUeX6Wt2CJWF6orH?usp=sharing)\n\n*Before running the Colab, edit Cell 1 and replace:* \n* \`YOUR_EMAIL\` with your IITM exam email\n* \`NGROK_TOKEN\` with your ngrok auth token\n\n---\n\n### 🚀 Submission Guide\n\n**Using the pre-deployed proxy (recommended):**\n1. Open the Ollama Proxy Hub: [Ollama Proxy Hub](${directUrl})\n2. Follow the on-screen setup steps.\n3. Copy the verified ngrok URL and submit it to the exam portal.\n\n---\n\n### 🛠️ Manual Ollama + ngrok Setup\n\n**Step 1: Install Ollama**\n\`\`\`bash\n# macOS / Linux\ncurl -fsSL https://ollama.ai/install.sh | sh\n\n# Windows: Download from https://ollama.ai/download\n\`\`\`\n\n**Step 2: Pull and run a model**\n\`\`\`bash\nollama pull llama3.2\nollama serve   # Starts on http://localhost:11434\n\`\`\`\n\n**Step 3: Expose via ngrok**\n\`\`\`bash\n# Install ngrok from https://ngrok.com/download\nngrok http 11434\n\`\`\`\n\n**Step 4: Get your public URL**\n- ngrok will display a URL like: \`https://abcd-1234.ngrok-free.app\`\n- Test it: \`curl https://abcd-1234.ngrok-free.app/api/tags\`\n- Submit this URL (without trailing slash) to the exam portal.\n\n**⚠️ Important notes:**\n- The model must respond to OpenAI-compatible chat completion requests.\n- Keep the ngrok tunnel and Ollama server running during exam validation.\n- Free ngrok URLs expire after ~2 hours — start close to submission time.`,
  };
}
